### ISSUE TITLE
Failed jobs?

### ISSUE THREAD

**Issue by dzerbino** [Ensembl/postgap#118]

**Comment by dzerbino** [comment]
Out of 171 missing EFOs in Postgap output:
- 107 were an uncaught failure (Ensembl REST went down for a moment on Jan 8th)
- 42 were not tested because not found in the GWAS Catalog at the time of running
- 14 unable to map SNPs to  genome because SNP IDs are not rsIDs
- 5 unable to map SNPs to genome, but could not reproduce bug (fluke?)
- 1 failure of LSF to start job properly (EFO_0001061) (Presumably a fluke)
- 1 no gene could not be mapped to GRCh38 (EFO_0008230)
- 1 oddball (EFO_0005193): I find it in the output file, possibly dropped in OTar pipeline.

**Comment by wnewell** [comment]
>42 were not tested because not found in the GWAS Catalog at the time of running.

The generation of EFOs in the makefile uses input from gwas SNP sources other than GWAS Catalog. The EFO list generation method in the makefile could be modified to use only EFO codes present in the GWAS Catalog.

**Comment by dzerbino** [comment]
Careful, these 42 were in your list of EFOs in Open Target but not Postgap, so the Makefile is not at fault for those.

Regarding the Makefile, I have a number of private changes (i.e. on my disk and not on GitHub) that pertain to Open Targets specific requests, and these changes ensure only GWAS Catalog EFOs are used as input to the pipeline. I have not pushed them out partly because they are OT specific, and partly because some must remain private for security reasons.
