### ISSUE TITLE
Modify Makefile to generate EFO list from GWAS Catalog only

### ISSUE THREAD

**Issue by wnewell** [Ensembl/postgap#122]

**Comment by dzerbino** [comment]
I've double checked, and all the [EFOs you listed as not being in GWAS Catalog](https://00e9e64bac85b94e52040e011c2188b70474364e2b4f788cae-apidata.googleusercontent.com/download/storage/v1/b/postgap-data/o/efos_venn%2Fefos_pg20180108_not_gwascat20180101.txt?qk=AD5uMEuQRnQKyrw6Sd6adzNpH0nfiICcjiPxQRf2AYd84vuAJ1stK22mvQP05vvWUjUNz5_GlotXiqeYe7GWU9f1oE8ja5vMpPUZwBOk2IjoM5eS7ru5udqvkHGF7PnfTlWUaixkqp7DgWyXq5hBAdAw__6QtlmyoUK54S0_xgMxYSarVtt9DtFoKPDIKUODCYa_RKwui9q9DpD0OMBUONr6fGPuW7Qolp-BgKzbk6Yz3dgFLy4tR1lUjK3_nxwTvHCk8knLGAxLrBge3s8Qc1-GVARNvI-ZMRbXoWM4RtOdS0ZnTRdNmKWht_LKieNRuiiN3VLRvB-UAIyX88_x-_O1DzBr-NceT8LEfHw8wGY3dnQv2UJIXsLawL0I7oLOSLN4AUgQbDoFFP-KJEOQNYZ3jEBEiJYDhkQfrwCqVEwguXdvToic9wW2SEqI17z5hUq3xb9Flir-mQAE8dozaXU4tZI7GAncvRZIvNVOzLGbfv3eXItqWT7QXMBsaOCbNZi01aeU6Hp3MXzoSi1q21aWd84nH38Nd2z18smmFZKttJiOKOqzbAsBnPat2moD8rpWe1Gwc4p4GNsBN0YpFd_cjFDMkOncxGeMnQB5iDD8f1D2EEAhipHJGjDJ-TgRUiCqiLu048hIjCrfMi1KjaZNZENU6I38DYs1yl_GBiiy7wFi8fYetMZGhK0B7TXNu0gC0g5VZ3sw5aktZF1jJ8OVQH8U0HKGWpaxoy15dLzG9zwTK3gPETEFe2kDndeRe5aI5GeQXHXUKjLrGjWR-x6EqS6206KC7g) show up in my download of GWAS Catalog (dated Dec 5th). This is therefore not an issue.
