### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by dzerbino** [Ensembl/postgap#13]
Hello @wnewell @willgdjones @elipapa,

1/ As requested by Gautier a few weeks ago, I put a version tag on the master branch. Current version is v0.1.0

The numbering system will be:

- increment of the top (left) digit: when we go from beta (v0) to production-ready (v1), or when we later redesign the pipeline in a radical way (typically with Verena's Bayesian method, v2)

- increment of the middle digit: these updates require a refresh of the local database files, or something similarly involved.

- increment of the last digit: minor bug fixes etc. Just a code change.

2/ Speaking of, I would like to push a few changes that will affect the local file structure (correcting 1000 Genomes file names, introducing Hi-C). William, let me know when would be a good time to push those changes onto master. They are currently waiting patiently on side branches.

Cheers,

Daniel

**Comment by wnewell** [comment]
Hi Daniel,

Please push everything onto master, and I'll update my version.

Thanks,
William

**Comment by dzerbino** [comment]
OK, I'll do it tomorrow ~1pm. I'll keep you posted.
