### ISSUE TITLE
Add a command line option to accept a GWAS SNP as input, to run LD expansion before gene assignment

### ISSUE THREAD

**Issue by wnewell** [Ensembl/postgap#136]
Add a command line option to run POSTGAP from a SNP that would be treated as a GWAS SNP, e.g. "python POSTGAP.py --gwas_rsID rs10009124".

This would call the method "gwas_snps_to_genes" in Integration.py, rather than "ld_snps_to_genes"

i.e. it would first run the LD expansion, then do the functional genomics assignments for the original SNPs AND the LD-associated SNPs.

**Comment by dzerbino** [comment]
This will be embedded in the Bayesian model (in prep)
