### ISSUE TITLE
Missing columns in output from running POSTGAP on a single SNP

### ISSUE THREAD

**Issue by wnewell** [Ensembl/postgap#137]
Several of the SNP and Gene columns that are output when running POSTGAP for an EFO ID are missing from the output when running POSTGAP for a single SNP.

The missing columns are:
- GRCh38 chromosome for the SNP
- GRCh38 position for the SNP
- GRCh37 chromosome for the gene
- GRCh37 position for the gene TSS
- GRCh38 chromosome for the gene
- GRCh38 position for the gene TSS

**Comment by dzerbino** [comment]
I think we should consider deprecating the single SNP mode in favour of the direct input of GWAS SNPs that is about to come.
