### ISSUE TITLE
adding tissue-specific regulatory annotation in Reg.py

### ISSUE THREAD

**Issue by zgturan** [Ensembl/postgap#154]
I downloaded CAPE_eQTLfrom https://www.ncbi.nlm.nih.gov/research/snpdelscore/rawdata/ under databases. There are 45 tissue-specific files for CAPE_eQTL. I want to write some code that enters the CAPE_eQTL folder and adding each file as a column in POSTGAP. My function did not do it. Here it is :

```
class CAPE_eQTL(Reg_source):
    display_name = "CAPE_eQTL"
    def run(self, ld_snps, tissues):
        print('i am here')
        
        tissues_f=fnmatch.filter(os.listdir('databases/CAPE_eQTL/'), '*.bed')
        
        add=[]
        print(tissues_f)
        for tf in tissues_f:
             print(tf)
             snp_hash = dict( (snp.rsID, snp) for snp in ld_snps)
             intersection = postgap.BedTools.overlap_snps_to_bed(ld_snps, postgap.Globals.DATABASES_DIR + '/CAPE_eQTL/' + tf)
             res = filter (lambda X: X.score, (self.get_cape_evidence(feature, snp_hash) for feature in intersection))
             print('before log')
             logging.info("\tFound %i regulatory variants in CAPE_eQTL" % (len(res)))
             print('after log')
             add+=res
        
        return add
    
    def get_cape_evidence(self, feature, snp_hash):
      return Regulatory_Evidence(
        snp = snp_hash[feature[7]],
        source = self.display_name,
    score = float(feature[3]),
        study = None,
        tissue = None,
        info = None
        )  
```

**Comment by dzerbino** [comment]
What was the output or error message?

**Comment by zgturan** [comment]
Code just added one .bed file as a column of POSTGAP output, but there should be two. Because I run it all .bed files (E126.bed, E127.bed) under the CAPE_eQTL folder. The following lines are the last column of POSTGAP output that is coming from E126.bed.

```cat res.txt | cut -f101 | head```

```
CAPE_eQTL
0.4112
0.3538
0.8918
0.5279
0.2603
0.2669
0.2984
0.4358
0.646
```

**Comment by dzerbino** [comment]
The returned RegulatoryEvidence objects does not distinguish between the source of the data, therefore the pipeline has no way of knowing that there are two files underlying this adaptor.

Examine the eQTL endpoint to see how multiple tissues are encoded in a single adaptor.

**Comment by zgturan** [comment]
done
