### ISSUE TITLE
Summary stats CLI argument error

### ISSUE THREAD

**Issue by eric-czech** [Ensembl/postgap#157]
Hi, I noticed this in [POSTGAP.py#L125](https://github.com/Ensembl/postgap/blob/c300e473a26d365ff9f892b92022c1391a52dcc5/POSTGAP.py#L125):

```
if len(options.diseases) > 0 or len(expanded_efo_iris) > 0 or postgap.Globals.GWAS_SUMMARY_STATS_FILE is not None > 0:
```

The last clause, ```postgap.Globals.GWAS_SUMMARY_STATS_FILE is not None > 0```, doesn't work correctly because the ">" operator takes precedence (e.g. ```'x' is not None > 0``` evaluates to False) so summary_stats arguments are currently being ignored there.  It's fine if you remove the trailing "> 0" though, so I'm guessing that was a typo.

**Comment by dzerbino** [comment]
D'oh, thanks for catching that!
