### ISSUE TITLE
Failed too many times to get a proper response for query http://grch37.rest.ensembl.org/vep/Human/id ! 

### ISSUE THREAD

**Issue by raonyguimaraes** [Ensembl/postgap#160]
Hi there,

I'm trying to run the following command and I'm getting a timeout error:
`
python POSTGAP.py --efos EFO_0003885`

`
requests.exceptions.ConnectionError: Failed too many times to get a proper response for query http://grch37.rest.ensembl.org/vep/Human/id ! `

I tried increasing the max_retries parameter to 100 in lib/postgap/REST.py but that didn't work as well.

If I type:

`python POSTGAP.py --disease autism`

It actually works! So I suspect it could be something related to the EFO terms I'm using being too big?

Please let me know what I could do to help solving this problem.

Thank you so much for your attention!

**Comment by dzerbino** [comment]
Hello @raonyguimaraes ,

This is possibly linked to the [Ensembl version release](http://www.ensembl.info/2020/04/29/ensembl-100-has-been-released/) on April 29. There is an interruption in services as things get updated. Things should soon get back to normal. 

Let us know if not,

Daniel

**Comment by raonyguimaraes** [comment]
Hi Daniel, thanks that is a good suggestion. I will try again.

**Comment by raonyguimaraes** [comment]
Hi Daniel,

I tried again. I didn't work!

These two commands are working:

python POSTGAP.py --disease diabetes
python POSTGAP.py --disease autism

Not If I try this one, it doesn't work:

time python POSTGAP.py --efos EFO_0003885 > postgap_multiple_sclerosis.tsv

requests.exceptions.ConnectionError: Failed too many times to get a proper response for query http://grch37.rest.e
nsembl.org/vep/Human/id !                           
                                                            
real    193m48.930s                                      
user    2m9.286s                                    
sys     0m40.360s                                  

Can someone try to run this command to check if it will run into the same problem?

**Comment by dzerbino** [comment]
Hello @raonyguimaraes ,

I also hit a bug, and will try to fix it in the next couple of days.

Thanks for raising this,

Daniel

**Comment by raonyguimaraes** [comment]
Could this be related?

https://github.com/Ensembl/postgap/commit/0453c91dfe4b911bc052137910fca093aac1ca8c

I will investigate this as well, I'm sure we can get this fixed. :)

**Comment by dzerbino** [comment]
I was thinking the same thing actually but did not have the time yet to test it out.

**Comment by dzerbino** [comment]
Hello @raonyguimaraes , 

Apologies for the slow turnaround, but I now managed to run the pipeline from end to end with a minor update to the Ensembl adaptor (now pushed on master).

Cheers,

Daniel
