### ISSUE TITLE
Tabix file required for VEP annotation

### ISSUE THREAD

**Issue by rozaimirazali** [Ensembl/postgap#161]
Hello. I am getting an error when running PostGAP as plugin for VEP. It is saying it needs a tbi file.

1. is there a tbi file for it ?

2. if not, would there be a problem if i re-organize the fields so that chromosome and position will be the first two columns and the ID move to the 3rd column ?

**Comment by dzerbino** [comment]
Hello @rozaimirazali ,

This is a question for the VEP team. Could you please write it to helpdesk@ensembl.org ? (I would normally forward your message to them but alas do not have your email address)

Cheers,

Daniel
