### ISSUE TITLE
post-GWAS pipeline, from bump to bump ?

### ISSUE THREAD

**Issue by jielab** [Ensembl/postgap#162]
Hi, 

I was searching for a pipeline that can basically automate all the major steps for analyzing GWAS results files.

Let's say that I download the Height GWAS from this resource http://geneatlas.roslin.ed.ac.uk/downloads/ and would like to the following common tasks:

1. Find ALL top independent loci. 

2. Label which of those loci are known (in GWAS Catalog, or in a list file that I provided ) or novel. 

3. Fine-mapping causal variants.

4. eQTL functional annotation etc. 

Don't know if this "open targets post-GWAS analysis pipeline" is supposed to do all these? 
I guess I don't need to use FUMA anymore.

Thank you & Best regards,
Jie

**Comment by dzerbino** [comment]
Dear @jiehuang001 ,

Yes, that is what our pipeline aims to do, however I cannot pronounce myself on the usefulness of FUMA. 

Cheers,

Daniel
