### ISSUE TITLE
HSTS ERROR, Python 3 ERROR, test command ERROR

### ISSUE THREAD

**Issue by jielab** [Ensembl/postgap#166]
Hi, there:

after I downloaded and unzipped postgap, I run: **sh scripts/installation/download.sh** 
However, I got the following error. Don't know if this affects something critical, or I could simply ignore it.
**===Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/jiehuang001/.wget-hsts'. HSTS will be disabled.**

When I run the test command: **python POSTGAP.py --disease autism  --database_dir databases**
I first run into error because my default python is python3. Don't know if and when the future version of POSTGAP would support python3.

Then I had to switch to Python2. But I now got the following error:
**Traceback (most recent call last):
  File "POSTGAP.py", line 40, in <module>
    import postgap
  File "/mnt/d/software_lin/postgap/postgap.py", line 41, in <module>
    import postgap.GWAS
ImportError: No module named GWAS**

Your help would be greatly appreciated. I feel POSTGAP would be a really cool tool, if it runs smoothly.

Thank you & best regards,
Jie

**Comment by dzerbino** [comment]
Dear @jielab ,

POSTGAP is indeed meant to be run with Python 2. I'm afraid I've no idea what this HSTS business is about, but that is neither here nor there. 

To allow Python to find the GWAS module, you need to set the `$PYTHONPATH` variable to point to the `lib` directory in the repo (see instructions).

Hope this helps,

Daniel

**Comment by jielab** [comment]
Dear Daniel:

Please see the screenshot below. I did set the PYTHONPATH environmental variable in the ~/.bashrc file. 
But it still says no GWAS module.

![11](https://user-images.githubusercontent.com/26947455/101302354-5ea37880-3876-11eb-9a4c-410890c06746.JPG)


Can you please let me know what is happening here.

Thank you & best regadrs,
Jie

**Comment by dzerbino** [comment]
Dear @jielab ,

Could you please confirm where postgap was installed? 

According to your `$PYTHONATH` it is installed in `/mnt/d/software_lin/postgap/` but according to you shell prompt it is installed in `/mnt/d/software_lin/postgap-master/`

Best regards,

Daniel

**Comment by jielab** [comment]
Dear Daniel: 

I first installed it into "postgap" folder and set the PYTHONPATH variable accordingly. I still got the error.
Later on, someone suggested me to rename "postgap" to "postgap-master". I forgot the change the PYTHONPATH.

Please see the attached screenshot below. It still does not work.

![11](https://user-images.githubusercontent.com/26947455/101419570-3c1f6700-392b-11eb-9b48-d164f51830fb.JPG)

Thank you & best regards,
Jie

**Comment by dzerbino** [comment]
Hello @jielab ,

This is odd. Could you please confirm that `/mnt/d/software_lin/postgap/lib/postgap/GWAS.py` exists?

Cheers,

Daniel

**Comment by jielab** [comment]
Dear Daniel:

Yes, it does exist. Please see the screenshot below.

![11](https://user-images.githubusercontent.com/26947455/101550351-1b6a1680-39ea-11eb-8e1e-f28624df3415.JPG)



Best regards,
Jie

**Comment by dzerbino** [comment]
Very curious indeed... 

I'm wondering, why does the stack trace mention a file called `/mnt/d/software_lin/postgap/postgap.py`. Is there such a file? Normally, there should only be `/mnt/d/software_lin/postgap/POSTGAP.py`?

**Comment by jielab** [comment]
Dear Daniel:

Below shows all the files inside the postgap directory.

![11](https://user-images.githubusercontent.com/26947455/101712350-4b8be500-3ad0-11eb-8295-e905c082b241.JPG)

My student told me that he made it work by removing the postgap.pyc file and rename the "postgap" directory to something else. Somehow it does not work for me.

Best regards,
Jie

**Comment by jielab** [comment]
The error message seems to says that:
line 40 of POSTGAP.py is "import postgap", which somehow refers to the file of /mnt/d/software_lin/postgap/postgap.py, which somehow could not load the module GWAS.

**Comment by dzerbino** [comment]
Hello @jielab ,

Could you please: 

- delete `/mnt/d/software_lin/postgap/postgap.py`
- ensure `/mnt/d/software_lin/postgap/` is one of the options in $PYTHONPATH

... then let me know if it works?

Thank you,

Daniel

**Comment by jielab** [comment]
Dear Daniel:

Please see the attached screenshot below. I removed the postgap.pyc file and added postgap directory to $PYTHONPATH.

![12](https://user-images.githubusercontent.com/26947455/101844388-3d4cd000-3b87-11eb-9640-4045297013b8.JPG)


But it still does not work.

Best regards,
Jie

**Comment by dzerbino** [comment]
Hello @jielab 

Sorry, I just realised something, could you please re-try the above, but with only `/mnt/d/software_lin/postgap/lib/` in the PYTHONPATH?

Clearly Python thinks the `/mnt/d/software_lin/postgap/` directory is a library, but I do not understand why.

Also, to confirm, when you are using Python 2, you are using Python 2.7, correct?

Thank you,

Daniel

**Comment by jielab** [comment]
Dear Daniel:

Please see the screenshot below. I did as you advised, but still the same error message.

![11](https://user-images.githubusercontent.com/26947455/101967818-37262480-3c57-11eb-8f10-be1658d774df.JPG)

Best regards,
Jie
