### ISSUE TITLE
How to get the disease name for RSID

### ISSUE THREAD

**Issue by Sububioinfo** [Ensembl/postgap#169]
Hi i have run the eg but am not getting the file with 100 columns, only am getting  15 columns. 
I am looking for the disease names for the RSID can you help me to solve the issuses. 
python POSTGAP.py --rsID rs10009124
snp_rsID        chrom   pos     gene_symbol     gene_id score   GTEx    VEP     Fantom5 DHS     PCHiC   Nearest Regulome        VEP_reg GERP
rs10009124      4       137094749       PCDH18  ENSG00000189184 1.0     0       0       0       0       0       1.0

**Comment by dzerbino** [comment]
Dear @Sububioinfo ,

You are right that the SNP search output could be updated, I'll look into this later today. Nonetheless, in the absence of GWAS results, Postgap alone cannot associate a SNP to a disease. 

You may be interested however in [precomputed postgap outputs in the VEP](https://github.com/Ensembl/VEP_plugins/blob/release/103/PostGAP.pm).

Hope this helps,

Daniel
