### ISSUE TITLE
Adapt Postgap for use with Conda

### ISSUE THREAD

**Issue by PlatonB** [Ensembl/postgap#170]
I tried to resolve dependencies not according to readme, but with Conda and APT.
```
conda install htslib vcflib bcftools vcftools bedtools libBigWig gsl WiggleTools pybedtools requests pandas flask cherrypy h5py
```
```
sudo apt install -y git gcc make g++ curl autoconf pkg-config libz-dev libbz2-dev liblzma-dev libcurl4-gnutls-dev libgsl-dev libsqlite3-dev libgl1-mesa-glx libegl1-mesa libxrandr2 libxrandr2 libxss1 libxcursor1 libxcomposite1 libasound2 libxi6 libxtst6 libssl-dev virtualenv
```

I was able to find all the dependencies in the Conda channels, except for the legacy `pysqlite`. There were also no problems with components delivered via APT.

Unfortunately, in this case the program is not functional. At a minimum, it is not possible to import `cPickle` and `postgap` modules.

My feature request is to make it possible to run Postgap after a simple two-command installation of dependencies via Conda and APT.

**Comment by dzerbino** [comment]
Hello @PlatonB , 

I'll have a look at this tomorrow, but is there a reason why you want to use only APT and Conda?

Specifically, last I checked (which was a while back TBH), pysqlite and cPickle were easily available via pip, would you be happy using pip?

Cheers,

Daniel

**Comment by PlatonB** [comment]
> but is there a reason why you want to use only APT and Conda?

install_dependencies.sh is capable of compiling a number of popular bioinformatics tools. But many bioinformatics already have this software installed via Conda. Running install script will flood the system with lots of duplicate software.

> Specifically, last I checked (which was a while back TBH), pysqlite and cPickle were easily available via pip, would you be happy using pip?

No, pip3 doesn't find them. By the way, why does the program use pysqlite when sqlite3 is part of the Python standart library?

**Comment by dzerbino** [comment]
Hello @PlatonB ,

You pointed out three problematic blocking points:

- pysqlite: actually this is a typo and was meant to be pysqlite3
- cPickle: this is available for Python2 on both pip and conda. Note that Postgap runs on Python2.7 for the moment, although we have plans to port to 3 shortly. 
- postgap: conda distribution of the postgap package has not been implemented yet, however it is just a bunch of Python files in the postgap directory, this can be copied directly from the Github repo onto a directory on your PYTHON_PATH (or your PYTHON_PATH could be changed, as you prefer)

Does this answer your question?

Cheers,

Daniel

**Comment by PlatonB** [comment]
> a directory on your PYTHON_PATH (or your PYTHON_PATH could be changed, as you prefer)

Please write in the readme a description of how to work with PYTHON_PATH. My actions were as follows:
`cd postgap-master/`
`python POSTGAP.py -h`
```
Traceback (most recent call last):
  File "POSTGAP.py", line 41, in <module>
    import postgap
ModuleNotFoundError: No module named 'postgap'
```

> Note that Postgap runs on Python2.7 for the moment

I assume this is the main explanation for all the problems outlined. Hopefully, after rewriting to Python 3, the installation will be painless for Conda users.

**Comment by dzerbino** [comment]
Hello @PlatonB ,

Assuming your current directory is the root directory of the repo, you have several options:

1. Copying the libraries to the default apt-get location: ```cp -R lib/postgap /usr/local/lib/python2.7/```
2. Copying the libraries to an existing location (probably the one created by Conda, although there may be others): ```cp -R lib/postgap `echo $PYTHON_PATH | tr ':' '\n' | grep -v ^$ | head -1` ```
3. Augment your PYTHON_PATH to point to that location: ```echo PYTHON_PATH=\$PYTHON_PATH:$PWD/lib/ >> ~./bashrc && source ~/.bashrc``` 

Hope this helps,

Daniel

**Comment by PlatonB** [comment]
1. Executing the command works, but does not lead to the desired result.
2.
```
cp -R lib/postgap `echo $PYTHON_PATH | tr ':' '\n' | grep -v ^$ | head -1`
```
```
cp: missing destination file operand after 'lib/postgap'
Try 'cp --help' for more information.
```

3.
```
echo PYTHON_PATH=\$PYTHON_PATH:$PWD/lib/ >> ~./bashrc && source ~/.bashrc
```
```
-bash: ~./bashrc: No such file or directory
```

Distro: elementary OS 5.1.7 (based on Ubuntu 18.04.4)

**Comment by dzerbino** [comment]
1. Could you please tell me more about the observed results?
2. That is odd, do you have conda installed? 
3. is due to a typo, it should have been: 
```echo PYTHON_PATH=\$PYTHON_PATH:$PWD/lib/ >> ~/.bashrc && source ~/.bashrc```

**Comment by dzerbino** [comment]
D'oh! Something just hit me: it should be `PYTHONPATH`, not `PYTHON_PATH`, sorry!

**Comment by PlatonB** [comment]
```
cp -R lib/postgap `echo $PYTHONPATH | tr ':' '\n' | grep -v ^$ | head -1`
```
```
cp: 'lib/postgap' and '/home/platon/postgap-master/lib/postgap' are the same file
```

The error `No module named 'postgap'` still occurs.

> That is odd, do you have conda installed?

I have Conda installed with Python 3.7. I guess our discussion should be frozen until PostGap migrates to Python 3. P.S. Now I am trying to run PostGap inside VirtualBox using the official image.

**Comment by dzerbino** [comment]
OK, thanks, I'll let you know when the Python3 version is ready. In the mean time I'll close this conversation.
