### ISSUE TITLE
Change p-value threshold for summary statistics

### ISSUE THREAD

**Issue by 11Dmitriy11** [Ensembl/postgap#173]
Postgap by default works only with variants with p-value >5x10-8 from summary statistics file as I understand. Is there any possibility to change this threshold?

**Comment by dzerbino** [comment]
Hello @11Dmitriy11 ,

That's a good point. At present it is hard coded in `lib/postgap/Globals.py`, feel free to modify the value of `GWAS_PVALUE_CUTOFF`. 

Cheers,

Daniel
