### ISSUE TITLE
postGAP vs. FUMA

### ISSUE THREAD

**Issue by jielab** [Ensembl/postgap#175]
Hi, guys:

Can someone please kindly let me know what could be done in postGAP but not in FUMA?

I am kind of overwhelmed with various tools and try to understand why when I begin to try new tools. 
I am also asked by my student on this question. Last year, I asked them to learn FUMA, now I asked them to learn postGAP.

Thank you very much!

Best regards,
jie

**Comment by dzerbino** [comment]
Dear Jie,

FUMA and the post-GWAS analysis pipeline provide roughly similar utilities, in their different ways. 

We developed our tool with a view to enable locus-level finemapping analyses which *I believe* are not available in FUMA, and I am sure that there are things which FUMA does which our tool cannot do.

Regards,

Daniel
