### ISSUE TITLE
virtual machine/environment

### ISSUE THREAD

**Issue by mfazel** [Ensembl/postgap#176]
Hi, Where do you guys have a virtual machine for postgap? I couldn't find it.
I was trying to follow the instruction from README.md page but failed to install with error: "pysqlite is not supported on Python 3".
Is it possible for you to create a docker container for postgap or a conda environment script?
(I also tried to build the container using the DockerFile, but it fails with "ERROR: Command errored out with exit status 1: python setup.py egg_info...")

Thanks,
Mehdi

**Comment by dzerbino** [comment]
Dear Mehdi,

The VirtualBox VM lives at: http://ftp.ebi.ac.uk/pub/databases/post-gwas/postgap.ova

Hope this helps,

Daniel

**Comment by mfazel** [comment]
Thanks, 👍
