### ISSUE TITLE
PhyloP

### ISSUE THREAD

**Issue by dzerbino** [Ensembl/postgap#37]

**Comment by dzerbino** [comment]
Hit a technical issue, the VEP REST endpoint does not return PhyloP score on account of performance, looking into plan B.

**Comment by dzerbino** [comment]
Create Reg.py module, that computes PhyloP conservation at each SNP location. 
Consult Mathieu Muffato for fastest way to extract PhyloP scores along the genome.

**Comment by willmclaren** [comment]
Not just to say "VEP" to everything :-), but VEP can pull in phyloP scores from bigWig files.

Not currently supported on REST as it depends on external data, but available to local VEP either accessing a remotely hosted phyloP file or a local file. Example files at UCSC: http://hgdownload.cse.ucsc.edu/goldenpath/hg38/phyloP7way/ (GRCh38, but similar available for GRCh37.

**Comment by willmclaren** [comment]
Or of course we could just access the bigWig directly...

**Comment by dzerbino** [comment]
BigWig file at http://ftp.ensembl.org/pub/current_compara/conservation_scores/70_mammals.gerp_conservation_score/gerp_conservation_scores.homo_sapiens.bw
