### ISSUE TITLE
Investigate GWAS Cat lead SNPs that were dropped.

### ISSUE THREAD

**Issue by dzerbino** [Ensembl/postgap#40]

**Comment by dzerbino** [comment]
Hello @wnewell; could you please send me the list of offending SNPs (i.e. those returned by S2G but not PG)? Thanks!

**Comment by wnewell** [comment]
Hello @dzerbino. The list is on the ftp site: /upload/comparison_data.

**Comment by dzerbino** [comment]
Thanks!

**Comment by dzerbino** [comment]
Looking at the GWAS Catalog tables here: https://www.ebi.ac.uk/gwas/api/search/downloads/alternative

... I found that 1474 of the reported missing SNPs don't appear in GWAS catalog. List at upload/s2g_snps_not_in_gwas_catalog.txt

Now investigating the remaining 3358.

**Comment by dzerbino** [comment]
Oddly, all 3358 SNPs refer to 18 traits:
http://purl.obolibrary.org/obo/GO_0008150
http://purl.obolibrary.org/obo/GO_0042493
http://www.ebi.ac.uk/efo/EFO_0000001
http://www.ebi.ac.uk/efo/EFO_0000319
http://www.ebi.ac.uk/efo/EFO_0000405
http://www.ebi.ac.uk/efo/EFO_0000408
http://www.ebi.ac.uk/efo/EFO_0000540
http://www.ebi.ac.uk/efo/EFO_0000589
http://www.ebi.ac.uk/efo/EFO_0000616
http://www.ebi.ac.uk/efo/EFO_0000618
http://www.ebi.ac.uk/efo/EFO_0001444
http://www.ebi.ac.uk/efo/EFO_0004298
http://www.ebi.ac.uk/efo/EFO_0004324
http://www.ebi.ac.uk/efo/EFO_0004503
http://www.ebi.ac.uk/efo/EFO_0004529
http://www.ebi.ac.uk/efo/EFO_0004582
http://www.ebi.ac.uk/efo/EFO_0004732
http://www.ebi.ac.uk/efo/EFO_0004872

**Comment by dzerbino** [comment]
There appear to be several issues at hand:
- Some jobs failed for miscellaneous reasons
- The GWAS API does not return the same data as contained in the table above. Will contact Tony Burdett to investigate.

**Comment by wnewell** [comment]
The input SNPs to S2G are the SNPs in the November release of GWAS Catalog. The link in the URL is "gwas_catalog_v1.0.1-associations_e87_r2017-01-30", so it may be that the SNP IDs have been updated between the Nov'16 and Jan'17 GWAS Catalog releases.

**Comment by wnewell** [comment]
A quick check of the first few SNPs in the S2G GWAS SNP list shows that they are in the PG file, but in the "ld_snp_rsID" column (column 1), not the "gwas_snp_ids" column (column 9). Could this explain the discrepancy?

**Comment by wnewell** [comment]
I will update the comparison with the latest version of the assignments for GWAS Catalog - February release.

**Comment by wnewell** [comment]
From Mick's pipeline, SNP to Gene (S2G)

**Comment by dzerbino** [comment]
It feels rather odd for the GWAS Catalog to lose 1474 SNPs from one month to the next, but I will ask Tony. 

Regarding the ld_snp column, I really need to investigate more.

**Comment by dzerbino** [comment]
I had a look at the missing SNPs in the 20170613 dataset, and most of the failures I tested manually did not replicate. This is because a couple of weeks ago the GWAS Catalog team synched up their RESTFul servers with their main servers, so I believe the problem is solved, but needs to be verified on a new run. 

In the immediate future, the synching procedure will be manual, but the data will at most be a week or two out of sync.
