### ISSUE TITLE
Make sure MHC and olfactory regions are filtered out

### ISSUE THREAD

**Issue by dzerbino** [Ensembl/postgap#47]

**Comment by dzerbino** [comment]
Sent out request for regions.

**Comment by elipapa** [comment]
The question of applying alternative mapping approaches within HLA came up.  The simplest approach to this would be to use pairwise LD between all variants in HLA and the HLA 4-digit alleles, and report those that exceed a chosen threshold (e.g. r2 >= 0.7).  See the related paper from Paul de Bakker.
 
http://www.nature.com/ng/journal/v38/n10/abs/ng1885.html
