### ISSUE TITLE
Work around Ensembl's temporary anti-social error messages

### ISSUE THREAD

**Issue by dzerbino** [Ensembl/postgap#52]
Test with vep endpoint and 
data = {'ids': ['esv3647746', 'rs12628403', 'esv3647747', 'esv3647749']}

**Comment by willmclaren** [comment]
We can use a temporary REST server with fixed code.

https://github.com/Ensembl/postgap/commit/44c6e6f5cad84600bd81a4a9766b6d16a76b7f68 should help switching URL
