### ISSUE TITLE
Ensembl RegBuild overlap

### ISSUE THREAD

**Issue by dzerbino** [Ensembl/postgap#65]

**Comment by willmclaren** [comment]
VEP endpoints give you this already e.g. http://rest.ensembl.org/vep/human/id/rs567897082?content-type=application/json

**Comment by dzerbino** [comment]
This returns Regulatory_Evidence. However, the VEP is in Cisreg.py, as it returns Cisregulatory_Evidence objects. We could run VEP twice (which would be inefficient), or we could create a separate module for the VEP, for annotation systems that return both regulatory and cisregulatory objects.

**Comment by willmclaren** [comment]
VEP can also be used to lookup variant loci from rsIDs. If we switch to using a local install of VEP instead of REST calls this will be pretty efficient.

Might be good to consider a separate VEP module and then pull in evidence bits from that to each of the required places.

**Comment by dzerbino** [comment]
To resolve this ticket: augment the VEP so that the evidence it contains is based on overlap with Ensembl reg Build features
https://github.com/Ensembl/postgap/blob/master/lib/postgap/Reg.py#L185
