### ISSUE TITLE
Add columns "Source" and "p-value"

### ISSUE THREAD

**Issue by wnewell** [Ensembl/postgap#67]
Make 2 new columns for index SNPs, "Source" and "p-value", where "Source" is the GWAS data source that has the smallest p-value, and "p-value" is the smallest p-value in columns 14-17.

For non-index SNPs, these columns should have values of "NA", and "NaN" (or 1.0 following the current convention for "missing")

**Comment by dzerbino** [comment]
For a non-index SNP, wouldn't you want the p-value of the index SNP it is in LD with?

**Comment by wnewell** [comment]
Non-index SNPs have no a priori p-values with a trait/disease. 

It would be misleading to assign a p-value to them, as it might imply that they have themselves been found to be associated with a disease.

Better to use the r2 value linking the non-index SNP with the index SNP to  modify the score of the non-index SNP, as done in SG.

**Comment by dzerbino** [comment]
Certainly, but don't you want the p-value of the index SNP indicated on the same line as the r2, to avoid having to look it up elsewhere in the table?
