### ISSUE TITLE
Missing EFO terms for diseases

### ISSUE THREAD

**Issue by wnewell** [Ensembl/postgap#68]

**Comment by wnewell** [comment]
e.g. rs378854 / Prostate cancer / "N/A"

**Comment by wnewell** [comment]
![image](https://cloud.githubusercontent.com/assets/866658/25773286/fd84cb9c-3272-11e7-93d5-3c5ed1a3e51b.png)

**Comment by dzerbino** [comment]
This appears to be a GRASP phenotype. As discussed earlier, GRASP phenotypes could not be mapped to EFOs.
