### ISSUE TITLE
Disease names and reported traits from GWAS Catalog

### ISSUE THREAD

**Issue by gkos-bio** [Ensembl/postgap#69]
'disease_names' are really 'reported trait from GWAS' when it comes from the GWAS Catalog.
In Open Targets, we use the mapped ontology traits which means that you need to put both in your data representation.
What is not clear to us is why there is a difference between the 'disease_names' entries and the 'disease_efo_ids' entries. They look different when getting the labels from the EFO ids.

**Comment by dzerbino** [comment]
Hello @gkos-bio, 

could you please provide an example? I'm not sure I understand your comment.

Thanks,

Daniel

**Comment by dzerbino** [comment]
OK, so we need to report both reported and mapped URI.
