### ISSUE TITLE
Break up reports into 1 row per GWAS SNP

### ISSUE THREAD

**Issue by dzerbino** [Ensembl/postgap#72]

**Comment by wnewell** [comment]
Sorry, but for my purposes, i.e. building the database, the unexpanded file output would also be needed. That is, the original file format with multiple GWAS SNPs per line. Thanks.

**Comment by dzerbino** [comment]
Hello @wnewell,
We should think this through. Generating two massive files on account of a minor change in syntax is inefficient. Could you please explain why you and Gautier have different needs? Would it be simpler to simply generate one file from the other?
Daniel

**Comment by wnewell** [comment]
Hi @dzerbino. You're right. We can generate the larger file from the original file that you generated previously, if needed. The issue arose as it explained the order-of-magnitude difference in the number of data-points between POSTGAP (8M) and STOPGAP (94M). Talking account of multiple GWAS SNPs per line, POSTGAP is now ~50M.
This issue can be closed.

**Comment by dzerbino** [comment]
OK, so to be clear, I revert the behaviour to producing merged lines, which we then split up with a little post-processing script?

**Comment by wnewell** [comment]
Correct.
