### ISSUE TITLE
Additional columns in tabular output

### ISSUE THREAD

**Issue by wnewell** [Ensembl/postgap#78]
Based on discussions from last meeting (10/05/17) and after, it would be useful to have additional columns in the tabular output:

- VEP Max, VEP mean (VEP median?) in additional to the current VEP score, to take account of accumulation of VEP score over multiple transcripts
- MAF from 1k genomes LD SNPs - for the 4 population groups, and combined. Is  MAF also available for GWAS SNPs?
- PMID - for the associated GWAS SNP(s) from GWAS Catalog
- Reported Trait + Mapped Trait from GWAS Catalog

**Comment by dzerbino** [comment]
Points 1, 2 and 4 are covered by tickets #71, #49 and #69. 
Closing this ticket and replacing it with a new one for point 3.
