### ISSUE TITLE
postgap.EFO.suggest() is out of date

### ISSUE THREAD

**Issue by dzerbino** [Ensembl/postgap#85]
Hello @mn1 ,

Could you please look into this? 

Cheers,

Daniel

**Comment by mn1** [comment]
How are you running postgap and what error message do you get?

`python POSTGAP.py --database_dir /nfs/nobackup/ensembl/mnuhn/postgap/databases/ --diseases "diabetes" --output diabetes.tsv`

works for me.

**Comment by dzerbino** [comment]
```python POSTGAP.py  --database_dir /homes/zerbino/hps/postgap/databases --diseases "Blood cell traits, in red blood cells" --output  /homes/zerbino/hps/postgap/results/GRASP_string_4.out```

**Comment by mn1** [comment]
Ok, thanks, that fails for me too.

```
Traceback (most recent call last):
  File "POSTGAP.py", line 321, in <module>
    main()
  File "POSTGAP.py", line 93, in main
    efo_iris = filter(lambda X: X is not None, (postgap.EFO.suggest(disease) for disease in options.diseases))
  File "POSTGAP.py", line 93, in <genexpr>
    efo_iris = filter(lambda X: X is not None, (postgap.EFO.suggest(disease) for disease in options.diseases))
  File "/nfs/production/panda/ensembl/funcgen/software/postgap/postgap/lib/postgap/EFO.py", line 152, in suggest
    efo = hits[0]['semanticTags'][0]
IndexError: list index out of range
```

The problem is that zooma doesn't return any matches for "Blood cell traits, in red blood cells" and EFO.py doesn't check for that special case.

**Comment by dzerbino** [comment]
D'oh! Thanks.
