### ISSUE TITLE
Dependencies missing

### ISSUE THREAD

**Issue by Danilka** [Ensembl/postgap#95]
I tried to run this on Mac OSX and here are a few caveats I ran into:

- missing vcflib
- missing vcftools
- missing samtools
- missing bgzip
- had to rebuild gcc with -fopenmp support

Maybe you can add these dependencies in the future.

**Comment by dzerbino** [comment]
Hello @Danilka, 

Did you follow the instructions in the README? There is an install_dependencies script, which covers most of what you describe.

Cheers,

Daniel
