### ISSUE TITLE
Retrieve OR, CI, and Beta from GWAS data sources

### ISSUE THREAD

**Issue by wnewell** [Ensembl/postgap#99]
Retrieve Odds Ratios, 95% Confidence Intervals, and Betas from GWAS Catalog, and from the other sources where available, e.g. GRASP.

Report these values in the POSTGAP output, as additional GWAS SNP columns: "OR", "CI", "Beta", with each column having as many entries as there are GWAS SNPs for the given LD SNP being tested.

**Comment by wnewell** [comment]
Missing Confidence Intervals from GWAS Catalog.

**Comment by dzerbino** [comment]
This ticket is starting to get more technical. 

You can see how I resolved the first part of the ticket with [this commit](https://github.com/Ensembl/postgap/commit/8264cd06e418d6842264f58d06be4127bcea0bda). You may wish to through that commit and look for all occurrences of `odds_ratio`, as you will have to do something similar below:

1. In `lib/postgap/DataModel.py`: add a new key `odds_ratio_ci` to the definition of 'GWAS_Association'
2. In `lib/postgap/GWAS.py`: and ensure this new key is set to `None` each time the `GWAS_Association` constructor is called. 
3. In `lib/postgap/GWAS.py`: study the GWASCatalog.run function, and how it creates GWAS_Association objects
4. From the data provided by the GWAS Catalog (via the REST calls) find the confidence interval string, and use that to enter into the created object
6. In `POSTGAP.py`: insert a new column header, next to `odds_ratio`
7. In `POSTGAP.py`: write the odds_ratio_ci next to the odd_ration
